var tree = [["Omnimessage","Omnimessage.html","",
                [["MessageDispatchers","Omnimessage\/MessageDispatchers.html","",
                [["AbstractDispatcher","Omnimessage\/MessageDispatchers\/AbstractDispatcher.html","",
                [        ]],["Email","Omnimessage\/MessageDispatchers\/Email.html"," < AbstractDispatcher",
                [        ]],["HipChat","Omnimessage\/MessageDispatchers\/HipChat.html"," < AbstractDispatcher",
                [        ]],["Slack","Omnimessage\/MessageDispatchers\/Slack.html"," < AbstractDispatcher",
                [        ]],["Twilio","Omnimessage\/MessageDispatchers\/Twilio.html"," < AbstractDispatcher",
                [        ]],["Web","Omnimessage\/MessageDispatchers\/Web.html"," < AbstractDispatcher",
                [        ]]        ]],["Service","Omnimessage\/Service.html","",
                [["Exception","Omnimessage\/Service\/Exception.html"," < Exception",
                [        ]],["HipChat","Omnimessage\/Service\/HipChat.html","",
                [        ]],["Slack","Omnimessage\/Service\/Slack.html","",
                [        ]],["Twilio","Omnimessage\/Service\/Twilio.html","",
                [        ]],["Web","Omnimessage\/Service\/Web.html","",
                [        ]]        ]],["Exception","Omnimessage\/Exception.html"," < Exception",
                [        ]],["MultiDispatcher","Omnimessage\/MultiDispatcher.html","",
                [        ]],["Omnimessage","Omnimessage\/Omnimessage.html","",
                [        ]]        ]]        ]

