var tree = [["Omnimessage","Omnimessage.html","",
                [["MessageDispatcher","Omnimessage\/MessageDispatcher.html","",
                [["AbstractDispatcher","Omnimessage\/MessageDispatcher\/AbstractDispatcher.html","",
                [        ]],["Email","Omnimessage\/MessageDispatcher\/Email.html"," < AbstractDispatcher",
                [        ]],["HipChat","Omnimessage\/MessageDispatcher\/HipChat.html"," < AbstractDispatcher",
                [        ]],["Slack","Omnimessage\/MessageDispatcher\/Slack.html"," < AbstractDispatcher",
                [        ]],["Twilio","Omnimessage\/MessageDispatcher\/Twilio.html"," < AbstractDispatcher",
                [        ]],["Web","Omnimessage\/MessageDispatcher\/Web.html"," < AbstractDispatcher",
                [        ]]        ]],["Service","Omnimessage\/Service.html","",
                [["AbstractService","Omnimessage\/Service\/AbstractService.html","",
                [        ]],["Email","Omnimessage\/Service\/Email.html"," < AbstractService",
                [        ]],["Exception","Omnimessage\/Service\/Exception.html"," < Exception",
                [        ]],["HipChat","Omnimessage\/Service\/HipChat.html"," < AbstractService",
                [        ]],["Slack","Omnimessage\/Service\/Slack.html"," < AbstractService",
                [        ]],["Twilio","Omnimessage\/Service\/Twilio.html"," < AbstractService",
                [        ]],["Web","Omnimessage\/Service\/Web.html"," < AbstractService",
                [        ]]        ]],["Exception","Omnimessage\/Exception.html"," < Exception",
                [        ]],["MultiDispatcher","Omnimessage\/MultiDispatcher.html","",
                [        ]],["Omnimessage","Omnimessage\/Omnimessage.html","",
                [        ]]        ]]        ]

